[build]
  publish = "path/to/your/dist"  # This should be the directory where your built site is output to. Common values might be "dist", "public", "_site", etc.
  command = "npm i --force && your_build_command"
